### ISSUE TITLE
I have a problem when run 1_Pcap2Session

### ISSUE THREAD

**Issue by BeStrongok** [yungshenglu/USTC-TK2016#2]
it raise a error like this: 
Could not load type of field 'SplitCap.Program:pcapWriters' (7) due to: Could not load file or assembly 'PacketParser, Version=1.5.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
how can i solve this problem? thank you!!

**Comment by davidyslu** [comment]
Sorry for late response due to business traveling. Please give some time and review the problem. Really appreciate.

**Comment by BeStrongok** [comment]
> Sorry for late response due to business traveling. Please give some time and review the problem. Really appreciate.

I have solved this problem, because the '0_Tool' file is incomplete

**Comment by WithHades** [comment]
> > Sorry for late response due to business traveling. Please give some time and review the problem. Really appreciate.
> 
> I have solved this problem, because the '0_Tool' file is incomplete

I face the same quetion。
when I run the ./1_Pcap2Session.ps1  
the error is：
表达式或语句中出现意外标记“_Tool\SplitCap_2-1\SplitCap.exe”。
所在位置 E:\temp\USTC-TK2016\1_Pcap2Session.ps1:13 字符: 34
+     0_Tool\SplitCap_2-1\SplitCap.exe <<<<  -p 50000 -b 50000 -r $f.FullName -o 2_Session\AllLayers\$($f.BaseName)-ALL
    + CategoryInfo          : ParserError: (_Tool\SplitCap_2-1\SplitCap.exe:String) [], ParseException
    + FullyQualifiedErrorId : UnexpectedToken

and when I run the ： PS E:\temp\USTC-TK2016> E:\temp\USTC-TK2016\0_Tool\SplitCap_2-1\SplitCap.exe -p 5000 -b 5000 -r E:\temp\USTC-TK2016\1_Pcap\BitTorrent.pcap -o 2_Session\AllLayers\BitTorrent-ALL
the error is :
未处理的异常:  System.TypeInitializationException: “SplitCap.Program”的类型初始值设定项引发异常。 ---> System.IO.FileN
otFoundException: 未能加载文件或程序集“PacketParser, Version=1.5.0.0, Culture=neutral, PublicKeyToken=null”或它的某一
个依赖项。系统找不到指定的文件。
文件名:“PacketParser, Version=1.5.0.0, Culture=neutral, PublicKeyToken=null”
   在 SplitCap.Program..cctor()

**Comment by davidyslu** [comment]
Hi @WithHades,
Have you download the tool and put it into the folder `0_tool/` ?

**Comment by WithHades** [comment]
> Hi @WithHades,
> Have you download the tool and put it into the folder `0_tool/` ?

thx.
I modified the code and it's working.
now the code is:
.\0_Tool\SplitCap_2-1\SplitCap.exe -p 50000 -b 50000 -r $f.FullName -o 2_Session\AllLayers\$($f.BaseName)-ALL

**Comment by davidyslu** [comment]
Hi @WithHades, thanks for your solution.

**Comment by Muhammadkamrul** [comment]
Solution:
https://codeantenna.com/a/eAH9QevoZf
https://codeantenna.com/a/DaLNqiHmjb
