### ISSUE TITLE
Split_Cap lack of three dll

### ISSUE THREAD

**Issue by smithCoderLeo** [yungshenglu/USTC-TK2016#3]
SplitCap.exe need ****NetworkWrapper.dll** and **PacketParser.dll** and **PcapFileHandler.dll**
please download new SplitCap.zip from https://www.netresec.com/index.ashx?page=SplitCap

**Comment by davidyslu** [comment]
Hi @smithCoderLeo, thanks for your helping. Could you please give me a pull request on the `master` branch (for Windows).

**Comment by smithCoderLeo** [comment]
https://github.com/echowei/DeepTraffic/
可以看这个链接，我还是新手，真的不好意思，不太会用github，我按你说的试一下

**Comment by yahiko-l** [comment]
> SplitCap.exe need ****NetworkWrapper.dll** and **PacketParser.dll** and **PcapFileHandler.dll**
> please download new SplitCap.zip from https://www.netresec.com/index.ashx?page=SplitCap

Yes, I  run the 1_Pcap2Session.ps1 by the new version SplitCap. Thank you very much!

**Comment by davidyslu** [comment]
This issue has been solved in this [PR](https://github.com/yungshenglu/USTC-TK2016/pull/15).
