### ISSUE TITLE
I have a problem when run 1_Pcap2Session

### ISSUE THREAD

**Issue by panguo-cug** [yungshenglu/USTC-TK2016#6]
Error: No files matched '2_Session\AllLayers'
No files to process
Error: No files matched '2_Session\L7'
No files to process

**Comment by kremolmao** [comment]
I have the same problem.

**Comment by linparkkin** [comment]
Hi, I solved it by extracting the .pcap files from the relative folders (e.g. the 'Malware' and 'Benign' folder) and putting them into the '1_Pcap' folder. The PowerShell script does not iterate through directories in '1_Pcap'.
I had also to put the missing .DLL files to make SplitCap work (you can find them [here](https://github.com/echowei/DeepTraffic/tree/master/2.encrypted_traffic_classification/2.PreprocessedTools/0_Tool/SplitCap_2-1))

**Comment by Muhammadkamrul** [comment]
> Error: No files matched '2_Session\AllLayers' No files to process Error: No files matched '2_Session\L7' No files to process
Solution:
https://codeantenna.com/a/eAH9QevoZf
