### ISSUE TITLE
运行.\1_Pcap2Session.ps1时出错

### ISSUE THREAD

**Issue by mynewstart** [yungshenglu/USTC-TK2016#9]
Error: No files matched '2_Session\AllLayers'
Error: No files matched '2_Session\L7'

**Comment by xiongruoting** [comment]
请问作者，解决了这个问题吗

**Comment by Muhammadkamrul** [comment]
> Error: No files matched '2_Session\AllLayers' Error: No files matched '2_Session\L7'

https://codeantenna.com/a/eAH9QevoZf
